version: "3"

services:
  server:
      restart: always
      env_file:
        - ./config.env
      volumes:
        - ./:/srv
      build: .
      extra_hosts:
        - "host.docker.internal:host-gateway"
