version: "3"

services:
  server:
      networks:
        - florgon-pastes-bot
      restart: always
      env_file:
        - ./config.env
      volumes:
        - ./:/srv
      build: .

networks:
  florgon-pastes-bot:
